### ISSUE TITLE
Listado de articulos

### ISSUE THREAD

**Issue by nicolasrivadeneira** [nicolasrivadeneira/OnlyProject#1]
Agregar rubro y subrubro
Sacar costo
Cambiar %ganancia por precios.
Agregar filtros http://www.w3schools.com/howto/howto_js_filter_table.asp
Agregar modal para ver detalle de articulo

**Comment by nicolasrivadeneira** [comment]
igual que #19

**Comment by herpuccia** [comment]
Error En Filtros. Los Filtros no andan ningunos.

**Comment by nicolasrivadeneira** [comment]
Agregar para que se pueda agregar/descontar stock
