### ISSUE TITLE
ABM Rubro

### ISSUE THREAD

**Issue by nicolasrivadeneira** [nicolasrivadeneira/OnlyProject#16]

**Comment by herpuccia** [comment]
Al dar de alta o modificar una Marcar (Rubro) la aplicación permite ingresar porcentajes mayores a 100 % como también porcentajes negativos.

**Comment by herpuccia** [comment]
Al eliminar una Marca (Rubro) lo elimina directamente SIN preguntar si desea eliminarlo.
