### ISSUE TITLE
ABM Subrubro

### ISSUE THREAD

**Issue by nicolasrivadeneira** [nicolasrivadeneira/OnlyProject#17]

**Comment by herpuccia** [comment]
Eliminar arroja ERROR: An exception occurred while executing 'DELETE FROM articulo WHERE id = ?' with params [25]:

**Comment by herpuccia** [comment]
Al dar de Alta o Modificar un Producto (Subrubro) el sistema permite que es ingrese porcentajes Mayores que 100 como también porcentajes Negativos

**Comment by herpuccia** [comment]
Plantilla: "Listado de Articulos de subrubro xx de la Marca yy". Modificar el ancho de las columnas de la tabla pora que quede bien centrado. 
Además modificar el único input de esa tabla de manera que permita aumentar como también disminuir el stock. Me parece que en ningún lado del sistema está la opción de disminuir el stock. 
Todo esto lo puedo hacer yo, si a vos te parece.
Despues lo hablamos.

**Comment by herpuccia** [comment]
Agregué este comentario para re-abrir esta tarea.
