### ISSUE TITLE
Generar Factura PDF

### ISSUE THREAD

**Issue by nicolasrivadeneira** [nicolasrivadeneira/OnlyProject#2]

**Comment by nicolasrivadeneira** [comment]
Deberia restar del stock la cantidad a imprimir

**Comment by nicolasrivadeneira** [comment]
Ver si se puede trabajar con modal de bootstrap

**Comment by nicolasrivadeneira** [comment]
-Cambiar los filtros de busqueda de articulo: YO
-Preguntar cuando se imprima si se quiere restar el stock o no: HERNAN

**Comment by herpuccia** [comment]
Los filtros tanto de la pantalla: "Remito - Seleccionar Cliente" como el de la pantalla: "Seleccionar Articulos" NO andan cuando lo que se busca está en la segunda pagina. 
Cuando se busca algo en la pagina actual SI anda.

**Comment by nicolasrivadeneira** [comment]
@herpuccia el precio no esta bien. Debe calcular el precio segun el tipo de cliente que se seleccionó en la pantalla anterior, y vos siempre estas mostrando el precio para consumidor final
