### ISSUE TITLE
ABM Cliente

### ISSUE THREAD

**Issue by nicolasrivadeneira** [nicolasrivadeneira/OnlyProject#21]

**Comment by herpuccia** [comment]
Al dar de alta a un cliente permite ingresar:
En la Razón Social un nro. negativo. 
En nombre permite ingresar numeros.
Tel un nro negativo.
Cuit permite ingresar letras. 

El caso de prueba que usé es con el nombre: Miguel 45214, el cual quedó grabado.

**Comment by herpuccia** [comment]
Al eliminar un cliente explota.
