### ISSUE TITLE
Nomenclaturas

### ISSUE THREAD

**Issue by nicolasrivadeneira** [nicolasrivadeneira/OnlyProject#52]
Cambiar nomenclaturas de rubro a Marca y subrubro a Producto en todas las vistas

**Comment by herpuccia** [comment]
No pude cambiar la etiqueta: "rubro" en la siguiente vista: "Nuevo Producto". Se accede desde el menú mediante: Gestion Producto > Producto > Nuevo. 
Es lo único que falta para cerrar ésta Issues. 
Yo no pude hacerlo. Te pido que lo hagas y luego cerra la tarea.
