### ISSUE TITLE
Alta de un producto para una marca determinada.

### ISSUE THREAD

**Issue by herpuccia** [nicolasrivadeneira/OnlyProject#59]
Cuando damos de alta un producto para la marca determinada, por ej. rubro 0 en la lista desplegable Marca, nos deja seleccionar otra marca. 
Esta lista desplegable debería estar en modo NO EDITABLE.

**Comment by nicolasrivadeneira** [comment]
NOO!!, agregue ese campo a propósito para que sea mas flexible para el usuario (a pedido de él ademas). De esta manera puede agregar productos de otras marcas. Basta de agregar cosas por agregar, solo corregir los errores útiles
