### ISSUE TITLE
Action subrubrosAction de articuloController

### ISSUE THREAD

**Issue by herpuccia** [nicolasrivadeneira/OnlyProject#60]
Este "Action" se usa o ejecuta?
Porque la línea: " $rubro_id = $request->request->get('rubro_id');" me parece que tiene error de sintaxis.

**Comment by nicolasrivadeneira** [comment]
Si se ejecuta cuando seleccionas un rubro para los filtros o cuando creas un nuevo articulo q te traiga los subrubos de ese articulo. Por que decis que tiene error de sintaxis?

**Comment by nicolasrivadeneira** [comment]
Si esto esta resuelto, cerralo
