### ISSUE TITLE
Generar Remito

### ISSUE THREAD

**Issue by herpuccia** [nicolasrivadeneira/OnlyProject#61]
En la pantalla donde se carga la cantidad, % Descuento, importe correo, etc. Si hacemos clic en el botón cancelar el remito se guarda con estado abierto y con todos los artículos cargados, pero los datos ingresados como ser: "cantidad, % Descuento, importe correo, etc" no se guardan. 
Corregir esto para que los datos que se ingresaron hasta el momento también se guarden.

**Comment by nicolasrivadeneira** [comment]
Al seleccionar los articulos no se carga en primera instancia el subtotal y total

**Comment by nicolasrivadeneira** [comment]
No hace falta
