### ISSUE TITLE
Deshabilitar cambiar moneda cuando el remito está cerrado.  

### ISSUE THREAD

**Issue by herpuccia** [nicolasrivadeneira/OnlyProject#62]
No permitir cambiar el tipo de moneda cuando el remito está cerrado (modo edición).

**Comment by nicolasrivadeneira** [comment]
esto por que ? @herpuccia

**Comment by nicolasrivadeneira** [comment]
Te diria que no deshabilites el menu, si no que te permita cambiarlo pero el remito va a seguir trabajando con la misma moneda que estaba antes. Se entiende?
Esta tarea la dejo abierta para que la cierres cuando resuelvas lo de setearle la moneda al remito

**Comment by nicolasrivadeneira** [comment]
Idem #65
