### ISSUE TITLE
MONEDA CUANDO SE LA PASA A LA VISTA: remitoitems.html.twig

### ISSUE THREAD

**Issue by herpuccia** [nicolasrivadeneira/OnlyProject#65]
Pensar cual es la mejor manera de implementar esto. 
Ver los controladores: remito_editar, remito_ver, entre otros.
Controlar las demás vistas.

**Comment by nicolasrivadeneira** [comment]
Lo que hay que hacer es setear la moneda al remito, y no el simbolo. De esta manera obtener el valor de la moneda cuando la opcion es igual VER.
Tener en cuenta que los reportes van a cambiar seguramente
