### ISSUE TITLE
DATA TABLES BOTONES EN LAS SOLAPAS SIGUIENTES

### ISSUE THREAD

**Issue by herpuccia** [nicolasrivadeneira/OnlyProject#67]
Ver como se hace porque NO recuerdo.
No andan los eliminar en todas las solapas que siguen a la solapa 1.

**Comment by nicolasrivadeneira** [comment]
@herpuccia creo que es con esta funcion:
$('#tableb').on('draw.dt', function () {
}

**Comment by herpuccia** [comment]
Si es eso.
