### ISSUE TITLE
Pantalla Cheques

### ISSUE THREAD

**Issue by herpuccia** [nicolasrivadeneira/OnlyProject#81]
Cuando un cheque es Rebotado, automaticamente el importe del cheque se debería sumar a la cuenta corriente. O se debería sacar ese cheque del listado de movimientos o marcar de alguna manera, para que no se tenga en cuanta en la cuenta corriente del cliente.

**Comment by nicolasrivadeneira** [comment]
Esto lo charle con tu hermano y me dijo que no haga nada, que se haga manualmente si se quiere devolver el importe
