### ISSUE TITLE
Formularios de Alta

### ISSUE THREAD

**Issue by herpuccia** [nicolasrivadeneira/OnlyProject#84]
En todos los FORMULARIOS de alta, implementar el "ENTER" para que el usuario pueda moverse al input siguiente. Esto trae 3 ventajas:
- Agiliza al usuario el ingreso de datos. 
- Elimina la posibilidad de que cuando se presiona sin intención el enter se haga un Submit. 
- El ingreso de datos queda consistente con el ingreso de datos que se hace en los Reportes.

**Comment by nicolasrivadeneira** [comment]
Esto es cierto, pero en php los formularios tienen por defecto el submit en el enter y deberia ser asi en todos los formularios. Para pasar de campos se debe presionar el TAB. A ver en un futuro
